#!/bin/bash
set -e

echo "=== Starting SMARTCAMPUS / RosarioSIS Container ==="

# Validate database environment variables
DB_SERVER="${DB_SERVER:-${DATABASE_SERVER:-db.ebyepweqwihdvjecrufk.supabase.co}}"
DB_USER="${DB_USER:-${DATABASE_USER:-postgres}}"
DB_PASSWORD="${DB_PASSWORD:-${DATABASE_PASSWORD:-}}"
DB_NAME="${DB_NAME:-${DATABASE_NAME:-postgres}}"
DB_PORT="${DB_PORT:-${DATABASE_PORT:-5432}}"
SUPABASE_SSL_MODE="${SUPABASE_SSL_MODE:-require}"
DEFAULT_SYEAR="${DEFAULT_SYEAR:-2026}"

if [ -z "$DB_PASSWORD" ]; then
    echo "[WARNING] DB_PASSWORD is not set. Database connection may fail."
fi

# Dynamically generate config.inc.php from runtime environment variables
echo "[INFO] Generating config.inc.php..."
cat << 'EOF' > /var/www/html/config.inc.php
<?php
/**
 * Dynamic RosarioSIS configuration generated by docker-entrypoint.sh
 */

$DatabaseType = 'postgresql';
$DatabaseServer = getenv('DB_SERVER') ?: (getenv('DATABASE_SERVER') ?: 'db.ebyepweqwihdvjecrufk.supabase.co');
$DatabaseUsername = getenv('DB_USER') ?: (getenv('DATABASE_USER') ?: 'postgres');
$DatabasePassword = getenv('DB_PASSWORD') ?: (getenv('DATABASE_PASSWORD') ?: '');
$DatabaseName = getenv('DB_NAME') ?: (getenv('DATABASE_NAME') ?: 'postgres');
$DatabasePort = getenv('DB_PORT') ?: (getenv('DATABASE_PORT') ?: '5432');

$wkhtmltopdfPath = '';
$DefaultSyear = getenv('DEFAULT_SYEAR') ?: '2026';
$RosarioNotifyAddress = '';
$RosarioErrorsAddress = '';
$RosarioLocales = ['en_US.utf8'];
$SupabaseSSLMode = getenv('SUPABASE_SSL_MODE') ?: 'require';
?>
EOF

chown www-data:www-data /var/www/html/config.inc.php
chmod 640 /var/www/html/config.inc.php

# Ensure assets directories exist and are writable
mkdir -p /var/www/html/assets/FileUploads /var/www/html/assets/StudentPhotos /var/www/html/assets/UserPhotos
chown -R www-data:www-data /var/www/html/assets/FileUploads /var/www/html/assets/StudentPhotos /var/www/html/assets/UserPhotos
chmod -R 775 /var/www/html/assets/FileUploads /var/www/html/assets/StudentPhotos /var/www/html/assets/UserPhotos

# Configure Apache port binding dynamically based on $PORT (Render provides PORT, default 10000)
LISTEN_PORT="${PORT:-10000}"
echo "[INFO] Configuring Apache to listen on port ${LISTEN_PORT}..."

# Rewrite ports.conf
cat << EOF > /etc/apache2/ports.conf
Listen ${LISTEN_PORT}
EOF

# Rewrite 000-default.conf with AllowOverride All
cat << EOF > /etc/apache2/sites-available/000-default.conf
<VirtualHost *:${LISTEN_PORT}>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html

    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog \${APACHE_LOG_DIR}/error.log
    CustomLog \${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
EOF

echo "[INFO] Entrypoint initialization complete. Starting Apache..."
exec "$@"
