/**
 * pwabuilder-sw.js — PWA Service Worker for SMARTCAMP-K12
 * Generated by PWA Builder — caches static assets for offline use
 * Strategy: Cache First (assets) + Network First (API/HTML)
 */

const CACHE_NAME = 'smartcamp-k12-cleanup-1';
const STATIC_ASSETS = [
  '/',
  '/index.php',
  '/public/css/tokens.css',
  '/public/css/base.css',
  '/public/css/components.css',
  '/public/js/main.js',
  '/public/js/reveal.js',
  '/public/js/stepper.js',
  '/public/js/enhancements.js',
  '/public/icons/icon-192.png',
  '/public/icons/icon-512.png',
  '/assets/images/logo.png',
  '/public/favicon.ico',
];

// Install — cache static assets
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(STATIC_ASSETS);
    })
  );
  self.skipWaiting();
});

// Activate — clean old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      );
    })
  );
  self.clients.claim();
});

// Fetch — serve from cache first, fall back to network
self.addEventListener('fetch', (event) => {
  const { request } = event;

  // Skip non-GET requests
  if (request.method !== 'GET') return;

  // Skip API calls and admin pages — always go to network
  if (
    request.url.includes('/api/') ||
    request.url.includes('/admin/') ||
    request.url.includes('healthz') ||
    request.url.includes('?nocache')
  ) {
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        // Cache successful responses (but not HTML pages — network-first for those)
        if (response.status === 200 && request.url.includes('/public/')) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, clone));
        }
        return response;
      });
    })
  );
});